# Generated by Django 5.0.6 on 2024-10-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_requestform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('reg_no', models.CharField(max_length=50)),
                ('or_no', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('chassis_no', models.CharField(max_length=50)),
                ('model_make', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
