# Generated by Django 5.0.6 on 2024-10-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_application_age_remove_application_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='photos',
        ),
        migrations.AlterField(
            model_name='application',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
