# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_application_photos_alter_application_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE),  # Fix is here
        ),
    ]
