# Generated by Django 5.0.6 on 2024-10-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
