# Generated by Django 5.0.6 on 2024-10-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_application_age_application_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
