# Generated by Django 5.0.6 on 2024-11-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_application_submitted_to_person2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='submitted_to_person2',
        ),
    ]
