# Generated by Django 5.0.6 on 2024-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_application_submitted_to_person2'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
