# Generated by Django 5.0.6 on 2024-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_client2_approved',
            field=models.BooleanField(default=False),
        ),
    ]
