# Generated by Django 5.0.6 on 2024-11-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_application_is_client2_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
