# Generated by Django 5.0.6 on 2024-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_application_paid_amount_application_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
