# Generated by Django 5.0.6 on 2024-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_application_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disapproved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
