# Generated by Django 5.0.6 on 2024-11-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_application_disapproved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='or_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='sticker_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
