# Generated by Django 5.0.6 on 2024-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_alter_application_app_status_alter_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='checked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
