# Generated by Django 5.0.6 on 2024-11-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_application_checked_by_alter_application_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.CharField(default='Applicant', max_length=50),
        ),
    ]
