# Generated by Django 5.0.6 on 2024-11-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
