# Generated by Django 5.0.6 on 2024-11-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_alter_application_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='picture_id',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='vehicle_register',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
