# Generated by Django 5.0.6 on 2024-11-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Checking Application', max_length=50),
        ),
    ]
