# Generated by Django 5.0.6 on 2025-07-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='payment_type',
        ),
        migrations.AlterModelTable(
            name='application',
            table='myApp_application',
        ),
    ]
