# Generated by Django 5.0.6 on 2025-07-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_remove_application_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_forwarded_to_person2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='person2_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
