# Generated by Django 5.0.6 on 2025-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_application_is_forwarded_to_person2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
