# Generated by Django 5.0.6 on 2025-07-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_application_approved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disapproved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
