# Generated by Django 5.0.6 on 2025-07-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_pushsubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
