# Generated by Django 5.0.6 on 2025-07-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_application_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
