# Generated by Django 5.0.6 on 2025-07-17 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_remove_application_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='is_subscribed',
        ),
    ]
