# Generated by Django 5.0.6 on 2025-07-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_profile_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='application',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='picture_id',
            field=models.ImageField(blank=True, null=True, upload_to='pictureId/'),
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_photos/')),
                ('category', models.CharField(choices=[('front', 'Front View'), ('side', 'Side View'), ('rear', 'Rear View (No Open Pipe)')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_photos', to='myApp.application')),
            ],
        ),
    ]
