# Generated by Django 5.2.4 on 2025-07-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0038_renewalform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalform',
            name='application',
        ),
    ]
