# Generated by Django 5.2.4 on 2025-07-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_remove_renewalform_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalform',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='renewals/license/'),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='orcr_file',
            field=models.ImageField(blank=True, null=True, upload_to='renewals/orcr/'),
        ),
    ]
