# Generated by Django 5.2.4 on 2025-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0040_renewalform_license_photo_renewalform_orcr_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalform',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='license/'),
        ),
        migrations.AlterField(
            model_name='renewalform',
            name='orcr_file',
            field=models.ImageField(blank=True, null=True, upload_to='orcr/'),
        ),
    ]
