# Generated by Django 5.2.4 on 2025-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0041_alter_renewalform_license_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalform',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
