# Generated by Django 5.2.4 on 2025-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0042_renewalform_address_renewalform_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalform',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
