# Generated by Django 5.2.4 on 2025-08-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_renewalform_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
