# Generated by Django 5.2.4 on 2025-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0044_profile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='application_signatures/'),
        ),
    ]
