# Generated by Django 5.2.4 on 2025-08-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0045_application_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='license_photo',
            new_name='license_photos',
        ),
    ]
