# Generated by Django 5.2.4 on 2025-08-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0046_rename_license_photo_application_license_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pipe_photos',
            field=models.ImageField(blank=True, null=True, upload_to='pipePhotos'),
        ),
        migrations.AddField(
            model_name='application',
            name='vehicle_photos',
            field=models.ImageField(blank=True, null=True, upload_to='vehiclePhotos'),
        ),
        migrations.DeleteModel(
            name='VehiclePhoto',
        ),
    ]
