# Generated by Django 5.2.4 on 2025-08-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0047_application_pipe_photos_application_vehicle_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalform',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
