# Generated by Django 5.2.4 on 2025-08-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0048_renewalform_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalform',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='renewalform',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.application'),
        ),
    ]
