# Generated by Django 5.2.4 on 2025-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0049_remove_renewalform_plate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalform',
            name='application',
        ),
        migrations.AddField(
            model_name='renewalform',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='engine_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='or_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='picture_id',
            field=models.ImageField(blank=True, null=True, upload_to='renewal_picture_ids/'),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='vehicle_register',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
