# Generated by Django 5.2.4 on 2025-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0050_remove_renewalform_application_renewalform_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
