# Generated by Django 5.2.4 on 2025-08-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0051_application_is_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalform',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='application_signatures/'),
        ),
    ]
