# Generated by Django 5.2.4 on 2025-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0052_renewalform_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalform',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
