# Generated by Django 5.2.4 on 2025-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0053_renewalform_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client2_approved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
