# Generated by Django 5.2.4 on 2025-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0054_application_client2_approved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signature2',
            field=models.ImageField(blank=True, null=True, upload_to='application_signatures/'),
        ),
    ]
