# Generated by Django 5.2.4 on 2025-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0055_application_signature2'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalform',
            name='signature2',
            field=models.ImageField(blank=True, null=True, upload_to='application_signatures/'),
        ),
    ]
