# Generated by Django 5.2.4 on 2025-08-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0056_renewalform_signature2'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='renewalform',
            name='user_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
