# Generated by Django 5.2.4 on 2025-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0059_profile_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
